monitor.alsa.rules = [
  {
    matches = [
      {
        device.bus = "usb"
        device.id.vendor = "045e"
        device.id.product = "02bb"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
